=== valyli/school.project/IT维护项目开发/知识表草稿/！！！！！信息表调用过程演示程序和源代码（含Client端调用演示程序程序，数据传输改用的是CManageData类）（2003-03-25）/DTD定义文件和引入这些DTD文件的XML文件（主文件名和XML文件的主文件名相同）/InfomationTable.dtd
<?xml version="1.0"?>
<!ELEMENT InfomationTable (InfoServiceProviderId,NameBaseId,InfomationElementTableID,InfomationElementSection+)>
<!ELEMENT InfoServiceProviderId (#PCDATA)>
<!ELEMENT NameBaseId (#PCDATA)>
<!ELEMENT InfomationElementTableID (#PCDATA)>
<!ELEMENT InfomationElementSection (InfomationElementID,Infomation,EnglishName,InfomationType,Description)>
<!ELEMENT InfomationElementID (#PCDATA)>
<!ELEMENT Infomation (#PCDATA)>
<!ELEMENT EnglishName (#PCDATA)>
<!ELEMENT InfomationType (#PCDATA)>
<!ELEMENT Description (#PCDATA)>

=== valyli/school.project/IT维护项目开发/知识表草稿/！！！！！信息表调用过程演示程序和源代码（含Client端调用演示程序程序，数据传输改用的是CManageData类）（2003-03-25）/DTD定义文件和引入这些DTD文件的XML文件（主文件名和XML文件的主文件名相同）/WindowsInfomationTable.xml
<?xml version="1.0" encoding="gb2312"?>
<!DOCTYPE InfomationTable SYSTEM "InfomationTable.dtd">
<InfomationTable>
	<InfoServiceProviderId>1</InfoServiceProviderId><NameBaseId>1</NameBaseId><InfomationElementTableID>1</InfomationElementTableID><InfomationElementSection><InfomationElementID>1</InfomationElementID><Infomation>系统版本</Infomation><EnglishName>System Version</EnglishName><InfomationType>5</InfomationType><Description>操作系统的版本信息</Description></InfomationElementSection></InfomationTable>
